baseurl                  = ""           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Didac Bigorda, Web Developer"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = ""
    homepage             = "main"                           # What to call the home page link
    footerText           = "Personal blog dedicated to code, travel and bananas."

# Metadata for Open Graph and Twitter
    description          = "Personal blog dedicated to code, travel and bananas"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Didac Bigorda"

[[params.mainMenu]]
    link = "/about"
    text = "I'm Dídac, a web developer"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/projects"
    text = "projects"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"


[imaging]
    quality = 75